# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8df6203f99674d9b6923a3ca28dc6f08"
application_url = "https://example.com"
embedded = true
name = "Ak dev app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
